language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy3"
install:
  - "pip install ."
  - "pip install 'sigtools>=0.1a4'"
  - "pip install -e git+https://github.com/epsy/clize.git#egg=clize"
  - "pip install pytest pytest-cov coveralls"
script:
  - "py.test -v --cov-config .coveragerc --cov spy"
after_success:
  - "coveralls"
