language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy3"
  - "pypy3.5-5.7.1-beta"
install:
  - "pip install --upgrade pip setuptools"
  - "pip install .[test]"
script:
  - "py.test -v --cov-config .coveragerc --cov spy"
after_success:
  - "coveralls"
