language: python
sudo: false
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy3"
env:
  - PYTEST_SELECTION=test
matrix:
  include:
    - name: "Python 3.6 without regression tests"
      python: "3.6"
      env: PYTEST_SELECTION="not regression"
install:
  - "pip install --upgrade pip setuptools coveralls"
  - "pip install -e .[test]"
script:
  - 'py.test -v -k "$PYTEST_SELECTION" --cov-config .coveragerc --cov spy'
after_success:
  - "coveralls"
