language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy3"
install:
  - "pip install ."
  - "pip install pytest pytest-cov coveralls"
script:
  - "py.test -v --cov-config .coveragerc --cov"
after_success:
  - "coveralls"
