language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
  - "pypy3"
  - "pypy3.5-5.8.0"
install:
  - "pip install --upgrade pip setuptools coveralls"
  - "pip install .[test]"
script:
  - "py.test -v --cov-config .coveragerc --cov spy"
after_success:
  - "coveralls"
